version: '3.2'
services:

    minio:
        container_name: minio
        image: minio/minio:RELEASE.2022-11-08T05-27-07Z
        command: server /data --console-address ":9001"
        ports:
            - "9001:9000"
            - "9002:9001"

    postgres:
        container_name: postgres
        image: postgres:12
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=airflow
            - POSTGRES_PORT=5432
        ports:
            - "5432:5432"
    zookeeper:
        container_name: zookeeper
        image: wurstmeister/zookeeper:latest
        ports:
            - "2181:2181"

    course-kafka:
        container_name: kafka
        image: wurstmeister/kafka:2.13-2.8.1
        environment:
            KAFKA_ADVERTISED_HOST_NAME: course-kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper

    kafdrop:
        container_name: kafdrop
        image: obsidiandynamics/kafdrop:3.30.0
        ports:
            - "9003:9000"
        environment:
            - KAFKA_BROKERCONNECT=course-kafka:9092
        depends_on:
            - course-kafka
            
    mariadb:
        container_name: maria_db
        image: mariadb:10.6
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: metastore_db
    
    hive-metastore:
        container_name: hive_metastore
        image: ofrir119/hive-metastore:1.0
        ports:
            - 9083:9083
        depends_on:
            - mariadb     
    dev_env:
        image: ofrir119/developer_env:spark340_ssh
        container_name: developer_env
        ports:
            - "22022:22"
            - "8888:8888"
            - "4040:4040"
            - "4041:4041"
            - "4042:4042"

    mongo:
        container_name: mongo
        image: mongo:6.0.13
        ports:
            - "27017:27017"
            
    nifi:
        image: apache/nifi:1.18.0
        container_name: nifi
        environment:
            - NIFI_WEB_HTTP_PORT=8080
        ports:
            - "8081:8080"
       
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
        ports:
            - "9200:9200"
        environment:
            discovery.type: single-node
            
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.13.2
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
    logstash:
        image: logstash:7.13.2
        container_name: logstash